// Copyright © 2017 The Things Network
// Use of this source code is governed by the MIT license that can be found in the LICENCE file.

/* @flow */
/* eslint-disable */
// Code generated by protoc-gen-flowtypes DO NOT EDIT.
// InputID: c2657807847526d478186d100593f64a2bde4ee5

export type Percentiles = {
  percentile1?: number,
  percentile5?: number,
  percentile10?: number,
  percentile25?: number,
  percentile50?: number,
  percentile75?: number,
  percentile90?: number,
  percentile95?: number,
  percentile99?: number
};

export type Rates = {
  rate1?: number,
  rate5?: number,
  rate15?: number
};

export type SystemStats = {
  load?: SystemStatsLoadstats,
  cpu?: SystemStatsCPUStats,
  memory?: SystemStatsMemoryStats
};

export type SystemStatsLoadstats = {
  load1?: number,
  load5?: number,
  load15?: number
};

export type SystemStatsCPUStats = {
  user?: number,
  system?: number,
  idle?: number,
  percentage?: number
};

export type SystemStatsMemoryStats = {
  total?: number,
  available?: number,
  used?: number
};

export type ComponentStats = {
  uptime?: number,
  cpu?: ComponentStatsCPUStats,
  memory?: ComponentStatsMemoryStats,
  goroutines?: number,
  gc_cpu_fraction?: number
};

export type ComponentStatsCPUStats = {
  user?: number,
  system?: number,
  idle?: number,
  percentage?: number
};

export type ComponentStatsMemoryStats = {
  memory?: number,
  swap?: number,
  heap?: number,
  stack?: number
};


