// Copyright © 2017 The Things Network
// Use of this source code is governed by the MIT license that can be found in the LICENCE file.

/* @flow */
/* eslint-disable */
// Code generated by protoc-gen-flowtypes DO NOT EDIT.
// InputID: 24a0d2ed25fabd4fdd91936b369efa24f693842b

export type LocationMetadataLocationSource = "GPS" | "CONFIG" | "REGISTRY" | "IP_GEOLOCATION";

export type LocationMetadata = {
  time?: number,
  latitude?: number,
  longitude?: number,
  altitude?: number,
  accuracy?: number,
  source?: LocationMetadataLocationSource
};

export type RxMetadata = {
  gateway_id?: string,
  gateway_trusted?: boolean,
  timestamp?: number,
  time?: number,
  encrypted_time?: string,
  rf_chain?: number,
  channel?: number,
  antennas?: Array<RxMetadataAntenna>,
  frequency?: number,
  rssi?: number,
  snr?: number,
  location?: LocationMetadata
};

export type RxMetadataAntenna = {
  antenna?: number,
  channel?: number,
  rssi?: number,
  channel_rssi?: number,
  rssi_standard_deviation?: number,
  frequency_offset?: number,
  snr?: number,
  encrypted_time?: string
};

export type TxConfiguration = {
  timestamp?: number,
  rf_chain?: number,
  frequency?: number,
  power?: number,
  polarization_inversion?: boolean,
  frequency_deviation?: number
};

export type Status = {
  timestamp?: number,
  time?: number,
  gateway_trusted?: boolean,
  boot_time?: number,
  ip?: Array<string>,
  platform?: string,
  contact_email?: string,
  description?: string,
  frequency_plan?: string,
  bridge?: string,
  router?: string,
  fpga?: number,
  dsp?: number,
  hal?: string,
  location?: LocationMetadata,
  rtt?: number,
  rx_in?: number,
  rx_ok?: number,
  tx_in?: number,
  tx_ok?: number,
  lm_ok?: number,
  lm_st?: number,
  lm_nw?: number,
  l_pps?: number,
  os?: StatusOSMetrics,
  messages?: Array<string>
};

export type StatusOSMetrics = {
  load_1?: number,
  load_5?: number,
  load_15?: number,
  cpu_percentage?: number,
  memory_percentage?: number,
  temperature?: number
};


