// Copyright © 2017 The Things Network
// Use of this source code is governed by the MIT license that can be found in the LICENCE file.

/* @flow */
/* eslint-disable */
// Code generated by protoc-gen-flowtypes DO NOT EDIT.
// InputID: 859739173a38e2f76c42bde9547aeb328b14d8fa

export type Message = {
  lorawan?: Message
};

export type RxMetadata = {
  lorawan?: Metadata
};

export type TxConfiguration = {
  lorawan?: TxConfiguration
};

export type ActivationMetadata = {
  lorawan?: ActivationMetadata
};


