// Copyright © 2017 The Things Network
// Use of this source code is governed by the MIT license that can be found in the LICENCE file.

/* @flow */
/* eslint-disable */
// Code generated by protoc-gen-flowtypes DO NOT EDIT.
// InputID: 141233775217bca80808075f49bdd65f3d96c98f

export type DeviceIdentifier = {
  app_eui?: string,
  dev_eui?: string
};

export type Device = {
  app_eui?: string,
  dev_eui?: string,
  app_id?: string,
  dev_id?: string,
  dev_addr?: string,
  nwk_s_key?: string,
  app_s_key?: string,
  app_key?: string,
  f_cnt_up?: number,
  f_cnt_down?: number,
  disable_f_cnt_check?: boolean,
  uses32_bit_f_cnt?: boolean,
  activation_constraints?: string,
  last_seen?: number
};


