// Copyright © 2017 The Things Network
// Use of this source code is governed by the MIT license that can be found in the LICENCE file.

/* @flow */
/* eslint-disable */
// Code generated by protoc-gen-flowtypes DO NOT EDIT.
// InputID: 48f2ea9a6731f54c33a6f3a12956b0a7c07eb5ca

export type DeviceActivationResponse = {
  payload?: string,
  message?: Message,
  downlink_option?: DownlinkOption,
  activation_metadata?: ActivationMetadata,
  trace?: Trace
};

export type StatusRequest = {

};

export type Status = {
  system?: SystemStats,
  component?: ComponentStats,
  uplink?: Rates,
  downlink?: Rates,
  activations?: Rates
};

export type ApplicationIdentifier = {
  app_id?: string
};

export type Application = {
  app_id?: string,
  payload_format?: string,
  decoder?: string,
  converter?: string,
  validator?: string,
  encoder?: string,
  register_on_join_access_key?: string
};

export type DeviceIdentifier = {
  app_id?: string,
  dev_id?: string
};

export type Device = {
  app_id?: string,
  dev_id?: string,
  lorawan_device?: Device,
  latitude?: number,
  longitude?: number,
  altitude?: number,
  attributes?: Array<DeviceAttributesEntry>,
  description?: string
};

export type DeviceAttributesEntry = {
  key?: string,
  value?: string
};

export type DeviceList = {
  devices?: Array<Device>
};

export type DryDownlinkMessage = {
  payload?: string,
  fields?: string,
  app?: Application,
  port?: number
};

export type DryUplinkMessage = {
  payload?: string,
  app?: Application,
  port?: number
};

export type SimulatedUplinkMessage = {
  app_id?: string,
  dev_id?: string,
  payload?: string,
  port?: number
};

export type LogEntry = {
  function?: string,
  fields?: Array<string>
};

export type DryUplinkResult = {
  payload?: string,
  fields?: string,
  valid?: boolean,
  logs?: Array<LogEntry>
};

export type DryDownlinkResult = {
  payload?: string,
  logs?: Array<LogEntry>
};


